### ISSUE TITLE
Denormalizing Data from Two Collections Before Importing into ElasticSearch

### ISSUE THREAD

**Issue by cyyapye** [compose/transporter#127] opened 2015-08-31 15:05 UTC
Hi,

I don't see a way of using transporter to denormalize data from two collections and merging them into one before importing into ElasticSearch. Is this correct or am I missing something?

Thanks.

**Comment by jipperinbham** [comment] 2015-08-31 17:32
Hi @cyyapye,

At the moment, that's not something it can do but is definitely on the roadmap, https://github.com/compose/transporter/issues/39. 

Going to close this one as a duplicate of #39 but feel free to reopen if I've missed what you're asking.

**Closed by jipperinbham** 2015-08-31 17:32 UTC
