### ISSUE TITLE
configure transporter on Ubuntu 16.04

### ISSUE THREAD

**Issue by damiano-vesperini** [compose/transporter#364] opened 2017-04-28 07:57 UTC
I follow all the step for install transporter on this guide (https://www.digitalocean.com/community/tutorials/how-to-sync-transformed-data-from-mongodb-to-elasticsearch-with-transporter-on-ubuntu-14-04)
After clone git repository, i move into transporter folder and both this command "go get -a ./cmd/..." 
"go build -a ./cmd/..."  give me this problem.

## Bug report
 github.com/compose/transporter/adaptor/rabbitmq
adaptor/rabbitmq/reader.go:69: u.Hostname undefined (type *url.URL has no field or method Hostname)

**Comment by codepope** [comment] 2017-04-28 08:27
Thats an old guide which we didn't write.

Follow the current build instructions as per the Readme - https://github.com/compose/transporter

(Simply `go build ./cmd/transporter/...`)

or use the binary releases of Transporter available here - https://github.com/compose/transporter/releases/tag/v0.3.1

The guide's configuration for Transporter is also out of date; Transporter has completely revised how it is configured into one easy to configure file and added many powerful new features in the process. Unfortunately, DigitalOcean's tutorials are not updated or removed.

**Comment by SamBartrum** [comment] 2017-06-01 13:35
I am also getting the same issue building as instructed in the Readme with just the go build ./cmd/transporter/... command.

**Comment by codepope** [comment] 2017-06-01 13:57
@SamBartrum as explained, this is an old guide. See my previous comment. We've been in touch with the author of the tutorial and he's preparing an update to it.

**Comment by SamBartrum** [comment] 2017-06-01 13:58
I was referring to your readme....

**Comment by codepope** [comment] 2017-06-01 14:03
Ah yes, good point.

**Comment by jipperinbham** [comment] 2017-06-01 15:29
I haven't been able to reproduce this issue on a local vagrant box, can you provide the following output from the below commands?

`go version`

within the transporter directory:
`git log --oneline | head -1`

**Comment by SamBartrum** [comment] 2017-06-06 16:25
Sorry I didn't reply sooner -  I was away. I was setting this up on an AWS EC2 Linux instance and have since switched to using your pre compiled binaries, which are working. If I run into the issue again, I'll post back on here. Thanks for your replies!

**Comment by jipperinbham** [comment] 2017-08-28 14:14
closing this as the binaries seem to work as expected for you, please feel free to re-open if needed

**Closed by jipperinbham** 2017-08-28 14:14 UTC

**Comment by hazel-nut** [comment] 2018-04-05 16:56
just a heads up — i've updated the tutorial on digitalocean. :)

https://www.digitalocean.com/community/tutorials/how-to-sync-transformed-data-from-mongodb-to-elasticsearch-with-transporter-on-ubuntu-16-04
