### ISSUE TITLE
 CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [11])

### ISSUE THREAD

**Issue by adeshpandey** [compose/transporter#141] opened 2015-09-25 12:24 UTC
After writing nearly 1639648 records transporter says this error and elastic search logs have nothing to show.

**Comment by Alino** [comment] 2015-09-26 13:57
this error should be more verbose I think, I never understood what this error means what is the root cause.

**Comment by adeshpandey** [comment] 2015-09-28 10:46
I do not have any other log for this

**Comment by jipperinbham** [comment] 2016-12-07 16:54
closing this in favor of https://github.com/compose/transporter/issues/209

**Closed by jipperinbham** 2016-12-07 16:54 UTC
