### ISSUE TITLE
Binary datatype changes to Document while sync from mongoDB to mongoDB

### ISSUE THREAD

**Issue by arumaidurai** [compose/transporter#429] opened 2017-10-17 14:40 UTC
I have setup a transporter from mongo to mongo, The mongodb contains the nutch 2.x crawl data of the internet web sites.

My  pipeline.js  file looks like the snippet below:
var source = mongodb({
  "uri": "mongodb://user:pwd@localhost:37001/srch"
});

var sink = mongodb({
  "uri": "mongodb://user:pwd@localhost:37001/srch"
});

t.Source("source", source, "/^crawl_webpage$/").Transform(pick({"fields":["_id", "baseUrl","content","contentType","title"]})). Transform("ns", otto({filename: "change-ns.js"}), "/.*/").Save("sink", sink, "/.*/")

The transformer.js is as below.

module.exports = function(msg)
{
  if (msg.ns=="crawl_webpage"){
        msg.ns="crawl_intranet";
  }
  if(msg.data["content"]==null || msg.data["content"]==""){
        msg.op = "skip";
  } 
console.log(JSON.stringify(msg, null, 2));
return msg;
}

### System info:

•Transporter version 0.5.0-linux-amd64
•OS  Red Hat Enterprise Linux Server release 6.9 (Santiago)   Linux 2.6.32-696.el6.x86_64 
•DB version(s)
 mongo - v2.0.4

### Reproducible Steps:

transporter-0.5.0-linux-amd64 run

### What did you expect to happened?
The datatype(org.bson.types.Binary) of the source mangodb collection field is getting changed to a different datatype(org.bson.Document) on the target mongoDB/Collection during the sync.

### What actually happened?
The datatype(org.bson.types.Binary) of the source mangodb collection field should remains same on the target mongodb collection.

**Comment by jipperinbham** [comment] 2017-11-14 14:59
I'm guessing this has to do with the version of MongoDB you're using (`mongo - v2.0.4`). I've tested against mongodb v2.6.9 and the binary data transferred properly. is there any way you can try against a newer version of mongodb?

**Comment by jipperinbham** [comment] 2017-12-12 14:31
looking through this a bit more, the issue is likely due to the multiple `Transform`s being used as we have to unmarshal/marshal the data back and forth for each function.

**Comment by arumaidurai** [comment] 2017-12-13 05:07
Thank you for the note. I have completed it using text data instead of
binary as the client is not moved on to latest version.

**Comment by jipperinbham** [comment] 2017-12-13 13:01
glad you got things worked out!

**Closed by jipperinbham** 2017-12-13 13:01 UTC
