### ISSUE TITLE
No data in Elasticsearch's indice after tranforming

### ISSUE THREAD

**Issue by roccia** [compose/transporter#165] opened 2016-01-21 07:17 UTC
everything works without errors, it seems that transporter is sending logs from mongo to es, cause the log entries keep showing in the Terminal, and also the indice was created by es , the only problem is there is no data in the new created indice, when I run:
         curl -XGET localhost:9200/tx_insight/latest/_search?pretty=true
 and the size of indice is 650b which never increase. dont know what is going on ..    wish someone can help me through this problem Thanks!
my config file : 

```
nodes:
  localmongo:
    type: mongo
    uri: mongodb://xx.xxx.xxx.xx/tx_insight
    namespace: tx_insight.latest
    tail: true
  es:
    type: elasticsearch
    uri: http://localhost:9200/
    namespace: tx_insight.latest
  timeseries:
    type: influx
    uri: influxdb://root:root@localhost:8086/compose
  debug:
    type: file
    uri: stdout://
  foofile:
    type: file
    uri: file:///tmp/foo
  logtransformer:
    filename: test/transformers/passthrough_and_log.js
    type: transformer
```

aplication.js

```
 Source({name:"localmongo", namespace:"tx_insight.latest", tail: true, bulk: true})
.transform({filename: "transformers/passthrough_and_log.js", namespace: "tx_insight.latest"})
.save({name:"es", namespace: "tx_insight.latest"})
```

**Comment by luncasu** [comment] 2016-01-27 19:53
Check ElasticSearch logs. I've hit same issue:
][DEBUG][action.bulk              ] [node-1] [foo][2] failed to execute bulk item (index) index {[foo][bar][56a8e4ec22ec6d812a081100], source[{"_id":"56a8e4ec22ec6d812a081100","firstName":"John","fullName":"John Snow","lastName":"Snow"}]}
MapperParsingException[Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]

**Comment by codepope** [comment] 2016-01-27 20:15
To explain, _id has been moved out of the document in ES2.x and promoted to a metadata field. The problem is that this means we can't assert the es _id equals the mongodb _id and that also causes issues with deletion. This could mean special casing the ES adapter (so that a "mongo _id" preserving field is named and created) or some other approach.

**Comment by roccia** [comment] 2016-02-01 01:27
is that means there are no solutions at the time?

**Comment by ndouba** [comment] 2016-02-03 20:20
This is creating duplicates in ES. The _id field has moved to the URL apparently as can be seen in the documentation:

```shell
#                                           id here
#                                               v                                                     
curl -XPUT 'http://localhost:9200/twitter/tweet/1' -d '{
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}'
```

**Comment by ndouba** [comment] 2016-02-04 21:03
Put together a pull request that should fix the problem (https://github.com/compose/transporter/pull/168)

**Comment by rgilling** [comment] 2016-02-10 19:05
I'm hitting this issue also importing to Elastic 2.1. I applied @luncasu  transform fix which changes the name to doc.id, but when I reimport docs it's causing duplicate entries. Is there any way now to explicitly set the id so it will overwrite rather than create new entries when the docs are imported?

**Comment by ndouba** [comment] 2016-02-10 23:09
@rgilling if you use my fix above all you have to do is move the value from `doc._id.$oid` to `doc._id` and you will avoid duplicates altogether.

**Comment by rgilling** [comment] 2016-02-11 00:36
Ok I'll give it a go today, I was using the binary release because I didn't want to set up the go environment. Any view to when it will get merged into the binary release? I can hold out for a few days it's just non production.

**Comment by rgilling** [comment] 2016-02-11 06:17
@ndouba I tried the patch, but I'm getting what I think is an unrelated issue from the latest build. It's only inserting the first document, then I get this exception in the log. Maybe something in the client changed and it's unrelated, but for now I can't test it because this is blocking.

```
[2016-02-11 06:10:54,706][DEBUG][cluster.service          ] [Living Monolith] processing [put-mapping [users]]: took 26ms done applying updated cluster_state (version: 13, uuid: 5PLH-98ASUeDR0U1Yo3EjA)
[2016-02-11 06:10:54,720][DEBUG][http.netty               ] [Living Monolith] Caught exception while handling client http traffic, closing connection [id: 0x4c44356d, /192.168.99.1:59818 :> /172.18.0.3:9200]
java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
	at org.jboss.netty.channel.Channels.write(Channels.java:725)
```

**Comment by ndouba** [comment] 2016-02-11 14:27
No idea :) I'm not part of the @compose team.

**Comment by ndouba** [comment] 2016-02-11 14:29
@rgilling Based on the error message it looks like you're http endpoint is abruptly shutting down the connection. I don't think it's related to transporter at all. Perhaps you are trying to connect to an HTTPS enabled elastic search using HTTP?

**Comment by jipperinbham** [comment] 2016-12-07 16:56
closing this in favor of https://github.com/compose/transporter/issues/209

**Closed by jipperinbham** 2016-12-07 16:56 UTC
